name: mongo_dart_query
version: 0.1.8
author: Vadim Tsushko <vadimtsushko@gmail.com>
description: Query builder for mongo_dart and objectory
homepage: https://github.com/vadimtsushko/mongo_dart_query
dependencies:
  bson: 
    version: '>=0.1.7 <2.0.0'
    git: git@github.com:SonarDesignInc/bson.git
dev_dependencies:
  browser: any
  unittest: any
